/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.formdev.flatlaf.FlatLightLaf;
import com.senati.proyecto.sistemapuntoventa.controller.UsuarioController;
import com.senati.proyecto.sistemapuntoventa.model.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class FrmMenu extends javax.swing.JFrame {    
    private final int usuarioId;
    private final UsuarioController usuarioController = new UsuarioController();
    public static JDesktopPane jDesktopPane;
    
    public FrmMenu(int usuarioId) {
        this.usuarioId = usuarioId;
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        mostrarUsuario();
        
        jDesktopPane = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        jDesktopPane.setBounds(0,0,ancho,(alto-100));
        this.add(jDesktopPane,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, ancho, (alto-110)));
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                String horaActual = sdf.format(new Date());
                tbxHora.setText(horaActual);
            }
        });

        timer.start();
        
        //System.out.println("ID del Usuario actual: "+ usuarioId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHotBar = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        tbxUsuario = new javax.swing.JTextField();
        lblPuesto = new javax.swing.JLabel();
        tbxPuesto = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        tbxHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        itemNuevoUsuario = new javax.swing.JMenuItem();
        itemGestionarUsuario = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenu();
        itemNuevaCategoria = new javax.swing.JMenuItem();
        itemGestionarCategoria = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenu();
        itemNuevoProducto = new javax.swing.JMenuItem();
        itemGestionarProducto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        itemNuevoCliente = new javax.swing.JMenuItem();
        itemGestionarCliente = new javax.swing.JMenuItem();
        menuFacturacion = new javax.swing.JMenu();
        itemNuevaVenta = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        itemHistorialUsuario = new javax.swing.JMenuItem();
        itemHistorialCategoria = new javax.swing.JMenuItem();
        itemHistorialProducto = new javax.swing.JMenuItem();
        itemHistorialCliente = new javax.swing.JMenuItem();
        itemHistorialVenta = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de ventas");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        pnlHotBar.setMaximumSize(new java.awt.Dimension(1908, 39));
        pnlHotBar.setMinimumSize(new java.awt.Dimension(1908, 39));
        pnlHotBar.setPreferredSize(new java.awt.Dimension(1908, 39));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblUsuario.setText("Usuario: ");

        tbxUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tbxUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxUsuario.setForeground(new java.awt.Color(0, 0, 0));
        tbxUsuario.setText("Usuario");
        tbxUsuario.setEnabled(false);

        lblPuesto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPuesto.setText("Puesto: ");

        tbxPuesto.setBackground(new java.awt.Color(255, 255, 255));
        tbxPuesto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxPuesto.setForeground(new java.awt.Color(0, 0, 0));
        tbxPuesto.setText("Puesto");
        tbxPuesto.setEnabled(false);

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblHora.setText("Hora:");

        tbxHora.setBackground(new java.awt.Color(255, 255, 255));
        tbxHora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxHora.setForeground(new java.awt.Color(0, 0, 0));
        tbxHora.setText("00:00:00");
        tbxHora.setEnabled(false);

        javax.swing.GroupLayout pnlHotBarLayout = new javax.swing.GroupLayout(pnlHotBar);
        pnlHotBar.setLayout(pnlHotBarLayout);
        pnlHotBarLayout.setHorizontalGroup(
            pnlHotBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1530, Short.MAX_VALUE)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHotBarLayout.setVerticalGroup(
            pnlHotBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHotBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHotBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblHora)
                    .addComponent(lblPuesto)
                    .addComponent(tbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        menuUsuario.setText("Usuarios");
        menuUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUsuario.setPreferredSize(new java.awt.Dimension(150, 50));

        itemNuevoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-usuario.png"))); // NOI18N
        itemNuevoUsuario.setText("Nuevo Usuario");
        itemNuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemNuevoUsuario.setPreferredSize(new java.awt.Dimension(220, 30));
        itemNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemNuevoUsuario);

        itemGestionarUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemGestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/habilidad.png"))); // NOI18N
        itemGestionarUsuario.setText("Gestionar Usuarios");
        itemGestionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemGestionarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemGestionarUsuario.setPreferredSize(new java.awt.Dimension(220, 30));
        itemGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemGestionarUsuario);

        jMenuBar1.add(menuUsuario);

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categorias.png"))); // NOI18N
        menuCategoria.setText("Categorías");
        menuCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuCategoria.setPreferredSize(new java.awt.Dimension(150, 50));

        itemNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        itemNuevaCategoria.setText("Nueva Categoría");
        itemNuevaCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNuevaCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevaCategoriaActionPerformed(evt);
            }
        });
        menuCategoria.add(itemNuevaCategoria);

        itemGestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aplicacion.png"))); // NOI18N
        itemGestionarCategoria.setText("Gestionar Categorias");
        itemGestionarCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemGestionarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarCategoriaActionPerformed(evt);
            }
        });
        menuCategoria.add(itemGestionarCategoria);

        jMenuBar1.add(menuCategoria);

        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto.png"))); // NOI18N
        menuProducto.setText("Productos");
        menuProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuProducto.setPreferredSize(new java.awt.Dimension(150, 50));

        itemNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto.png"))); // NOI18N
        itemNuevoProducto.setText("Nuevo Producto");
        itemNuevoProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNuevoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoProductoActionPerformed(evt);
            }
        });
        menuProducto.add(itemNuevoProducto);

        itemGestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productos.png"))); // NOI18N
        itemGestionarProducto.setText("Gestionar Productos");
        itemGestionarProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemGestionarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemGestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarProductoActionPerformed(evt);
            }
        });
        menuProducto.add(itemGestionarProducto);

        jMenuBar1.add(menuProducto);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        menuCliente.setText("Clientes");
        menuCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuCliente.setPreferredSize(new java.awt.Dimension(150, 50));

        itemNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/objetivo.png"))); // NOI18N
        itemNuevoCliente.setText("Nuevo Cliente");
        itemNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemNuevoCliente);

        itemGestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gestion-de-la-relacion-con-el-cliente.png"))); // NOI18N
        itemGestionarCliente.setText("Gestionar Clientes");
        itemGestionarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemGestionarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemGestionarCliente);

        jMenuBar1.add(menuCliente);

        menuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito.png"))); // NOI18N
        menuFacturacion.setText("Ventas");
        menuFacturacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFacturacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuFacturacion.setPreferredSize(new java.awt.Dimension(150, 50));

        itemNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nueva venta.png"))); // NOI18N
        itemNuevaVenta.setText("Nueva Venta");
        itemNuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNuevaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevaVentaActionPerformed(evt);
            }
        });
        menuFacturacion.add(itemNuevaVenta);

        jMenuBar1.add(menuFacturacion);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportes.png"))); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuReportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuReportes.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem12.setText("Reportes de Productos");
        jMenuItem12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuReportes.add(jMenuItem12);

        jMenuItem11.setText("Reportes de Clientes");
        jMenuItem11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuReportes.add(jMenuItem11);

        jMenuItem20.setText("Reportes de Ventas");
        jMenuItem20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuReportes.add(jMenuItem20);

        jMenuBar1.add(menuReportes);

        menuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historial1.png"))); // NOI18N
        menuHistorial.setText("Historial");
        menuHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuHistorial.setPreferredSize(new java.awt.Dimension(150, 50));

        itemHistorialUsuario.setText("Ver Historial de Usuarios");
        itemHistorialUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemHistorialUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemHistorialUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialUsuarioActionPerformed(evt);
            }
        });
        menuHistorial.add(itemHistorialUsuario);

        itemHistorialCategoria.setText("Ver Historial de Categorias");
        itemHistorialCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemHistorialCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemHistorialCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialCategoriaActionPerformed(evt);
            }
        });
        menuHistorial.add(itemHistorialCategoria);

        itemHistorialProducto.setText("Ver Historial de Productos");
        itemHistorialProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemHistorialProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemHistorialProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialProductoActionPerformed(evt);
            }
        });
        menuHistorial.add(itemHistorialProducto);

        itemHistorialCliente.setText("Ver Historial de Clientes");
        itemHistorialCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemHistorialCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemHistorialCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialClienteActionPerformed(evt);
            }
        });
        menuHistorial.add(itemHistorialCliente);

        itemHistorialVenta.setText("Ver Historial de Ventas");
        itemHistorialVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemHistorialVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemHistorialVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialVentaActionPerformed(evt);
            }
        });
        menuHistorial.add(itemHistorialVenta);

        jMenuBar1.add(menuHistorial);

        menuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion.png"))); // NOI18N
        menuCerrarSesion.setText("Cerrar Sesión");
        menuCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuCerrarSesion.setPreferredSize(new java.awt.Dimension(150, 50));

        itemCerrarSesion.setText("Cerrrar Sesión");
        itemCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        menuCerrarSesion.add(itemCerrarSesion);

        jMenuBar1.add(menuCerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHotBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHotBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // -Usuario-
    private void itemNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNuevoUsuarioActionPerformed

    private void itemGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarUsuarioActionPerformed

    // -Categoria-
    private void itemNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevaCategoriaActionPerformed
        InterNuevaCategoria interNuevaCategoria = new InterNuevaCategoria();
        jDesktopPane.add(interNuevaCategoria);
        interNuevaCategoria.setVisible(true);
    }//GEN-LAST:event_itemNuevaCategoriaActionPerformed

    private void itemGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarCategoriaActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_itemGestionarCategoriaActionPerformed

    // -Producto-
    private void itemNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoProductoActionPerformed
        InterNuevoProducto interProducto = new InterNuevoProducto();
        jDesktopPane.add(interProducto);
        interProducto.setVisible(true);
    }//GEN-LAST:event_itemNuevoProductoActionPerformed

    private void itemGestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarProductoActionPerformed
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);
    }//GEN-LAST:event_itemGestionarProductoActionPerformed

    // -Cliente-
    private void itemNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoClienteActionPerformed
        InterNuevoCliente interCliente = new InterNuevoCliente();
        jDesktopPane.add(interCliente);
        interCliente.setVisible(true);
    }//GEN-LAST:event_itemNuevoClienteActionPerformed

    private void itemGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarClienteActionPerformed
        InterGestionarCliente interGestionarCliente = new InterGestionarCliente();
        jDesktopPane.add(interGestionarCliente);
        interGestionarCliente.setVisible(true);
    }//GEN-LAST:event_itemGestionarClienteActionPerformed

    // -Venta-
    private void itemNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevaVentaActionPerformed
        InterVenta interVenta = new InterVenta(usuarioId);
        jDesktopPane.add(interVenta);
        interVenta.setVisible(true);
    }//GEN-LAST:event_itemNuevaVentaActionPerformed

    // -Cerrar Sesion-
    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        this.dispose();
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void itemHistorialUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemHistorialUsuarioActionPerformed

    private void itemHistorialCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialCategoriaActionPerformed
        InterHistorialCategoria interHistorialCategoria = new InterHistorialCategoria();
        jDesktopPane.add(interHistorialCategoria);
        interHistorialCategoria.setVisible(true);
    }//GEN-LAST:event_itemHistorialCategoriaActionPerformed

    private void itemHistorialProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialProductoActionPerformed
        try {
            InterHistorialProducto interHistorialProducto = new InterHistorialProducto();
            jDesktopPane.add(interHistorialProducto);
            interHistorialProducto.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir la ventana de historial de producto", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al abrir la ventana de historial de producto:\n" + e.getMessage());
        }
    }//GEN-LAST:event_itemHistorialProductoActionPerformed

    private void itemHistorialClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialClienteActionPerformed
        InterHistorialCliente interHistorialCliente = new InterHistorialCliente();
        jDesktopPane.add(interHistorialCliente);
        interHistorialCliente.setVisible(true);
    }//GEN-LAST:event_itemHistorialClienteActionPerformed

    private void itemHistorialVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialVentaActionPerformed
        InterHistorialVenta interHistorialVenta = new InterHistorialVenta();
        jDesktopPane.add(interHistorialVenta);
        interHistorialVenta.setVisible(true);
    }//GEN-LAST:event_itemHistorialVentaActionPerformed

    // -Hotbar-
    private void mostrarUsuario() {
        String nombreUsuario = obtenerUsuarioPorId(usuarioId, TipoInformacion.NOMBRE);
        String puestoUsuario = obtenerUsuarioPorId(usuarioId, TipoInformacion.PUESTO);

        tbxUsuario.setText(nombreUsuario);
        tbxPuesto.setText(puestoUsuario);
    }

    private String obtenerUsuarioPorId(int usuarioId, TipoInformacion tipoInformacion) {
        List<Usuario> listaUsuarios = usuarioController.listarUsuarios();
        for (Usuario usuario : listaUsuarios) {
            if (usuario.getId() == usuarioId) {
                switch (tipoInformacion) {
                    case NOMBRE:
                        return usuario.getNombre();
                    case PUESTO:
                        return usuario.getPuesto();
                }
            }
        }
        return tipoInformacion == TipoInformacion.NOMBRE ? "Usuario Desconocido" : "Puesto Desconocido";
    }
    enum TipoInformacion {
        NOMBRE, PUESTO
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura el tema FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemGestionarCategoria;
    private javax.swing.JMenuItem itemGestionarCliente;
    private javax.swing.JMenuItem itemGestionarProducto;
    private javax.swing.JMenuItem itemGestionarUsuario;
    private javax.swing.JMenuItem itemHistorialCategoria;
    private javax.swing.JMenuItem itemHistorialCliente;
    private javax.swing.JMenuItem itemHistorialProducto;
    private javax.swing.JMenuItem itemHistorialUsuario;
    private javax.swing.JMenuItem itemHistorialVenta;
    private javax.swing.JMenuItem itemNuevaCategoria;
    private javax.swing.JMenuItem itemNuevaVenta;
    private javax.swing.JMenuItem itemNuevoCliente;
    private javax.swing.JMenuItem itemNuevoProducto;
    private javax.swing.JMenuItem itemNuevoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFacturacion;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPanel pnlHotBar;
    private javax.swing.JTextField tbxHora;
    private javax.swing.JTextField tbxPuesto;
    private javax.swing.JTextField tbxUsuario;
    // End of variables declaration//GEN-END:variables
}