/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.senati.proyecto.sistemapuntoventa.controller.VentaController;
import com.senati.proyecto.sistemapuntoventa.model.Venta;
import com.senati.proyecto.sistemapuntoventa.controller.DetalleVentaController;
import com.senati.proyecto.sistemapuntoventa.model.DetalleVenta;
import com.senati.proyecto.sistemapuntoventa.controller.UsuarioController;
import com.senati.proyecto.sistemapuntoventa.model.Usuario;
import com.senati.proyecto.sistemapuntoventa.controller.ClienteController;
import com.senati.proyecto.sistemapuntoventa.model.Cliente;
import com.senati.proyecto.sistemapuntoventa.controller.ProductoController;
import com.senati.proyecto.sistemapuntoventa.model.Producto;

import com.toedter.calendar.JDateChooser;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JPanel;

public class InterHistorialVenta extends javax.swing.JInternalFrame {

    private VentaController ventaController = new VentaController();
    private DetalleVentaController detalleventaController = new DetalleVentaController();
    private UsuarioController usuarioController = new UsuarioController();
    private ClienteController clienteController = new ClienteController();
    private ProductoController productoController = new ProductoController();
    
    public InterHistorialVenta() {
        initComponents();
        inicializarCardLayouts();
        llenarTBLVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlFrame = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCuerpo = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        dcsFecha = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        btnExel = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlVentas = new javax.swing.JPanel();
        lblTituloVentas = new javax.swing.JLabel();
        scrVenta = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        pnlDetalle = new javax.swing.JPanel();
        lblTituloDetalle = new javax.swing.JLabel();
        scrDetalle = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Historial de Ventas");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        pnlFrame.setAlignmentX(0.0F);
        pnlFrame.setAlignmentY(0.0F);
        pnlFrame.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlFrame.setMaximumSize(new java.awt.Dimension(740, 445));
        pnlFrame.setMinimumSize(new java.awt.Dimension(740, 445));
        pnlFrame.setPreferredSize(new java.awt.Dimension(740, 445));

        pnlTitulo.setBackground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setForeground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setAlignmentX(0.0F);
        pnlTitulo.setAlignmentY(0.0F);
        pnlTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTitulo.setMaximumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(728, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Historial Ventas");
        lblTitulo.setAlignmentY(0.0F);
        lblTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCuerpo.setAlignmentX(0.0F);
        pnlCuerpo.setAlignmentY(0.0F);
        pnlCuerpo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlCuerpo.setMaximumSize(new java.awt.Dimension(175, 70));
        pnlCuerpo.setMinimumSize(new java.awt.Dimension(175, 70));
        pnlCuerpo.setPreferredSize(new java.awt.Dimension(175, 70));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRegresar.setText("Regresar al Registro");
        btnRegresar.setAlignmentY(0.0F);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setMargin(new java.awt.Insets(0, 5, 0, 5));
        btnRegresar.setMaximumSize(new java.awt.Dimension(175, 30));
        btnRegresar.setMinimumSize(new java.awt.Dimension(175, 30));
        btnRegresar.setPreferredSize(new java.awt.Dimension(175, 30));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        dcsFecha.setAlignmentX(0.0F);
        dcsFecha.setAlignmentY(0.0F);
        dcsFecha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dcsFecha.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        dcsFecha.setMaximumSize(new java.awt.Dimension(175, 30));
        dcsFecha.setMinimumSize(new java.awt.Dimension(175, 30));
        dcsFecha.setPreferredSize(new java.awt.Dimension(175, 30));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnBuscar.setText("Buscar Fecha");
        btnBuscar.setAlignmentY(0.0F);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setMargin(new java.awt.Insets(0, 5, 0, 5));
        btnBuscar.setMaximumSize(new java.awt.Dimension(175, 30));
        btnBuscar.setMinimumSize(new java.awt.Dimension(175, 30));
        btnBuscar.setPreferredSize(new java.awt.Dimension(175, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPDF.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btnPDF.setText("Descargar PDF");
        btnPDF.setAlignmentY(0.0F);
        btnPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPDF.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPDF.setMargin(new java.awt.Insets(0, 5, 0, 5));
        btnPDF.setMaximumSize(new java.awt.Dimension(175, 30));
        btnPDF.setMinimumSize(new java.awt.Dimension(175, 30));
        btnPDF.setPreferredSize(new java.awt.Dimension(175, 30));
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnExel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sobresalir.png"))); // NOI18N
        btnExel.setText("Descargar Excel");
        btnExel.setAlignmentY(0.0F);
        btnExel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExel.setMargin(new java.awt.Insets(0, 5, 0, 5));
        btnExel.setMaximumSize(new java.awt.Dimension(175, 30));
        btnExel.setMinimumSize(new java.awt.Dimension(175, 30));
        btnExel.setPreferredSize(new java.awt.Dimension(175, 30));
        btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExelActionPerformed(evt);
            }
        });

        pnlContenido.setAlignmentX(0.0F);
        pnlContenido.setAlignmentY(0.0F);
        pnlContenido.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlContenido.setLayout(new java.awt.CardLayout());

        pnlVentas.setAlignmentX(0.0F);
        pnlVentas.setAlignmentY(0.0F);
        pnlVentas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblTituloVentas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTituloVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVentas.setText("Registro de Ventas");
        lblTituloVentas.setAlignmentY(0.0F);
        lblTituloVentas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTituloVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTituloVentas.setMaximumSize(new java.awt.Dimension(525, 25));
        lblTituloVentas.setMinimumSize(new java.awt.Dimension(525, 25));
        lblTituloVentas.setPreferredSize(new java.awt.Dimension(525, 25));

        scrVenta.setAlignmentX(0.0F);
        scrVenta.setAlignmentY(0.0F);
        scrVenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrVenta.setMaximumSize(new java.awt.Dimension(525, 330));
        scrVenta.setMinimumSize(new java.awt.Dimension(525, 330));
        scrVenta.setPreferredSize(new java.awt.Dimension(525, 330));

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vendedor", "Cliente", "Fecha", "Descuento", "SubTotal", "IGV", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenta.setAlignmentX(0.0F);
        tblVenta.setAlignmentY(0.0F);
        tblVenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblVenta.setMaximumSize(new java.awt.Dimension(525, 330));
        tblVenta.setMinimumSize(new java.awt.Dimension(525, 330));
        tblVenta.setPreferredSize(new java.awt.Dimension(525, 330));
        tblVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentaMouseClicked(evt);
            }
        });
        scrVenta.setViewportView(tblVenta);
        if (tblVenta.getColumnModel().getColumnCount() > 0) {
            tblVenta.getColumnModel().getColumn(0).setResizable(false);
            tblVenta.getColumnModel().getColumn(1).setResizable(false);
            tblVenta.getColumnModel().getColumn(2).setResizable(false);
            tblVenta.getColumnModel().getColumn(3).setResizable(false);
            tblVenta.getColumnModel().getColumn(4).setResizable(false);
            tblVenta.getColumnModel().getColumn(5).setResizable(false);
            tblVenta.getColumnModel().getColumn(6).setResizable(false);
            tblVenta.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTituloVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pnlContenido.add(pnlVentas, "card2");

        pnlDetalle.setAlignmentX(0.0F);
        pnlDetalle.setAlignmentY(0.0F);
        pnlDetalle.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblTituloDetalle.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTituloDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDetalle.setText("Detalle de la Venta");
        lblTituloDetalle.setAlignmentY(0.0F);
        lblTituloDetalle.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTituloDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTituloDetalle.setMaximumSize(new java.awt.Dimension(525, 25));
        lblTituloDetalle.setMinimumSize(new java.awt.Dimension(525, 25));
        lblTituloDetalle.setPreferredSize(new java.awt.Dimension(525, 25));

        scrDetalle.setAlignmentX(0.0F);
        scrDetalle.setAlignmentY(0.0F);
        scrDetalle.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrDetalle.setMaximumSize(new java.awt.Dimension(525, 330));
        scrDetalle.setMinimumSize(new java.awt.Dimension(525, 330));
        scrDetalle.setPreferredSize(new java.awt.Dimension(525, 330));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio Uni.", "Cant.", "Desc.", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.setAlignmentX(0.0F);
        tblDetalle.setAlignmentY(0.0F);
        tblDetalle.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblDetalle.setMaximumSize(new java.awt.Dimension(525, 330));
        tblDetalle.setMinimumSize(new java.awt.Dimension(525, 330));
        tblDetalle.setPreferredSize(new java.awt.Dimension(525, 330));
        scrDetalle.setViewportView(tblDetalle);
        if (tblDetalle.getColumnModel().getColumnCount() > 0) {
            tblDetalle.getColumnModel().getColumn(0).setResizable(false);
            tblDetalle.getColumnModel().getColumn(1).setResizable(false);
            tblDetalle.getColumnModel().getColumn(2).setResizable(false);
            tblDetalle.getColumnModel().getColumn(3).setResizable(false);
            tblDetalle.getColumnModel().getColumn(4).setResizable(false);
            tblDetalle.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTituloDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pnlContenido.add(pnlDetalle, "card2");

        javax.swing.GroupLayout pnlCuerpoLayout = new javax.swing.GroupLayout(pnlCuerpo);
        pnlCuerpo.setLayout(pnlCuerpoLayout);
        pnlCuerpoLayout.setHorizontalGroup(
            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuerpoLayout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcsFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlCuerpoLayout.setVerticalGroup(
            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCuerpoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dcsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFrameLayout = new javax.swing.GroupLayout(pnlFrame);
        pnlFrame.setLayout(pnlFrameLayout);
        pnlFrameLayout.setHorizontalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(pnlCuerpo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        pnlFrameLayout.setVerticalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrameLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarCardLayouts() {
        LayoutManager layout = pnlContenido.getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cardLayoutContenido = (CardLayout) pnlContenido.getLayout();
            cardLayoutContenido.addLayoutComponent(pnlVentas, "pnlVentas");
            cardLayoutContenido.addLayoutComponent(pnlDetalle, "pnlDetalle");
        } else {
            System.err.println("Error: El layout de pnlContenido no es un CardLayout.");
        }
    }
    
    private void llenarTBLVenta() {
        List<Venta> listaVentas = ventaController.listarVentas();
        List<Usuario> listaUsuarios = usuarioController.listarUsuarios();
        List<Cliente> listaClientes = clienteController.listarClientes();


        DefaultTableModel model = (DefaultTableModel) tblVenta.getModel();
        model.setRowCount(0);
        
        for (Venta venta : listaVentas) {
            
            String nombreUsuario = "";
            for (Usuario usuario : listaUsuarios) {
                if (usuario.getId() == venta.getUsuario_id()) {
                    nombreUsuario = usuario.getNombre();
                    break;
                }
            }
            
            String nombreCliente = "";
            for (Cliente cliente : listaClientes) {
                if (cliente.getId() == venta.getCliente_id()) {
                    nombreCliente = cliente.getNombre();
                    break;
                }
            }
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String fechaFormateada = dateFormat.format(venta.getFecha_venta());
            
            Object[] rowData = {
                venta.getId(),
                nombreUsuario,
                nombreCliente,
                fechaFormateada,
                venta.getDescuento(),
                venta.getSubtotal(),
                venta.getIgv(),
                venta.getCantidad_total(),
            };
            model.addRow(rowData);
        }
    }
    
    private void cambiarPanel(CardLayout cardLayout, JPanel panel, String nombrePanel) {
        try {
            cardLayout.show(panel, nombrePanel);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error al cambiar al panel pnlDetalle:\n" + e.getMessage());
        }
    }
    
    private void tblVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentaMouseClicked
        int selectedRow = tblVenta.getSelectedRow();
        if (selectedRow != -1) {
            int ventaId = (int) tblVenta.getValueAt(selectedRow, 0);
            System.out.println("Venta seleccionada: " + ventaId);
            llenarTBLDetalle(ventaId);
            
            cambiarPanel((CardLayout) pnlContenido.getLayout(), pnlContenido, "pnlDetalle");
        }
    }//GEN-LAST:event_tblVentaMouseClicked
    
    private void llenarTBLDetalle(int ventaId) {
        List<DetalleVenta> listaDetalleVentas = detalleventaController.listarDetalleVentas();
        List<Producto> listaProductos = productoController.listarProductos();

        DefaultTableModel model = (DefaultTableModel) tblDetalle.getModel();
        model.setRowCount(0);

        for (DetalleVenta detalleventa : listaDetalleVentas) {
            if (detalleventa.getVenta_id() == ventaId) {
                String nombreProducto = "";
                for (Producto producto : listaProductos) {
                    if (producto.getId() == detalleventa.getProducto_id()) {
                        nombreProducto = producto.getNombre();
                        break;
                    }
                }

                Object[] rowData = {
                    detalleventa.getId(),
                    nombreProducto,
                    detalleventa.getPrecio_unitario(),
                    detalleventa.getCantidad(),
                    detalleventa.getDescuento(),
                    detalleventa.getPrecio_total(),
                };
                model.addRow(rowData);
            }
        }
    }
    
    private String obtenerFecha(JDateChooser dateChooser) {
        java.util.Date fecha = dateChooser.getDate();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(fecha);
    }    
    
    private void filtrarPorFecha(JTable tabla, String fechaSeleccionada, int columnaFecha) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        DefaultTableModel newModel = new DefaultTableModel();

        for (int i = 0; i < model.getColumnCount(); i++) {
            newModel.addColumn(model.getColumnName(i));
        }

        for (int i = 0; i < model.getRowCount(); i++) {
            String fechaEnTabla = model.getValueAt(i, columnaFecha).toString();
            if (fechaEnTabla.equals(fechaSeleccionada)) {
                Object[] rowData = new Object[model.getColumnCount()];
                for (int j = 0; j < model.getColumnCount(); j++) {
                    rowData[j] = model.getValueAt(i, j);
                }
                newModel.addRow(rowData);
            }
        }

        tabla.setModel(newModel);
    }    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String fechaSeleccionada = obtenerFecha(dcsFecha);
        filtrarPorFecha(tblVenta, fechaSeleccionada, 3);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    private void exportToExcel(JTable table, Workbook workbook, String sheetName) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        // Crea una hoja con el nombre proporcionado
        Sheet sheet = workbook.createSheet(sheetName);

        // Crea la fila de encabezados
        Row headerRow = sheet.createRow(0);
        for (int col = 0; col < model.getColumnCount(); col++) {
            Cell cell = headerRow.createCell(col);
            cell.setCellValue(model.getColumnName(col));
        }

        // Llena los datos
        for (int row = 0; row < model.getRowCount(); row++) {
            Row dataRow = sheet.createRow(row + 1);
            for (int col = 0; col < model.getColumnCount(); col++) {
                Cell cell = dataRow.createCell(col);
                cell.setCellValue(String.valueOf(model.getValueAt(row, col)));
            }
        }
    }    
    
    private void btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExelActionPerformed
        String descargasDirectory = System.getProperty("user.home") + "\\Downloads";
        String filePath = descargasDirectory + "\\Reporte_Ventas.xlsx";

        try (Workbook workbook = new XSSFWorkbook()) {
            exportToExcel(tblVenta, workbook, "Ventas");
            exportToExcel(tblDetalle, workbook, "Detalle");
            try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                workbook.write(fileOut);
                System.out.println("Excel creado exitosamente. Archivo: " + filePath);
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error al crear el archivo Excel: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExelActionPerformed
  
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        cambiarPanel((CardLayout) pnlContenido.getLayout(), pnlContenido, "pnlVentas");
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExel;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser dcsFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDetalle;
    private javax.swing.JLabel lblTituloVentas;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlCuerpo;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JScrollPane scrDetalle;
    private javax.swing.JScrollPane scrVenta;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblVenta;
    // End of variables declaration//GEN-END:variables
}
