/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.senati.proyecto.sistemapuntoventa.model.Cliente;
import com.senati.proyecto.sistemapuntoventa.controller.ClienteController;
import java.awt.CardLayout;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InterGestionarCliente extends javax.swing.JInternalFrame {
    
    private ClienteController clienteController = new ClienteController();
    
    public InterGestionarCliente() {
        initComponents();
        this.setSize(new Dimension(738,445));
        
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.addLayoutComponent(pnlTabla, "pnlTabla");
        cardLayout.addLayoutComponent(pnlEditar, "pnlEditar");
        
        llenarTabla();
        
        tblCliente.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                tblClienteMouseClicked(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWallpaper = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        scrCliente = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        pnlEditar = new javax.swing.JPanel();
        imgRegresar = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        tbxID = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        tbxNombre = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        tbxNumero = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        tbxDireccion = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        tbxDNI = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();

        lblWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        lblWallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.jpg"))); // NOI18N
        lblWallpaper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblWallpaper.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblWallpaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Cliente");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setMaximumSize(new java.awt.Dimension(738, 445));
        setMinimumSize(new java.awt.Dimension(738, 445));
        setName(""); // NOI18N
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(738, 445));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        pnlTitulo.setBackground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setForeground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setAlignmentX(0.0F);
        pnlTitulo.setAlignmentY(0.0F);
        pnlTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTitulo.setMaximumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(728, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CLIENTE");
        lblTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.setAlignmentX(0.0F);
        pnlContenido.setAlignmentY(0.0F);
        pnlContenido.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlContenido.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setPreferredSize(new java.awt.Dimension(728, 360));
        pnlContenido.setLayout(new java.awt.CardLayout());

        pnlTabla.setAlignmentX(0.0F);
        pnlTabla.setAlignmentY(0.0F);
        pnlTabla.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTabla.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setPreferredSize(new java.awt.Dimension(728, 360));

        scrCliente.setAlignmentX(0.0F);
        scrCliente.setAlignmentY(0.0F);
        scrCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        scrCliente.setMaximumSize(new java.awt.Dimension(714, 319));
        scrCliente.setMinimumSize(new java.awt.Dimension(714, 319));
        scrCliente.setPreferredSize(new java.awt.Dimension(714, 319));

        tblCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Numero", "Direccion", "DNI", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setAlignmentX(0.0F);
        tblCliente.setAlignmentY(0.0F);
        tblCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblCliente.setEditingColumn(0);
        tblCliente.setEditingRow(0);
        tblCliente.setMaximumSize(new java.awt.Dimension(714, 319));
        tblCliente.setMinimumSize(new java.awt.Dimension(714, 319));
        tblCliente.setPreferredSize(new java.awt.Dimension(714, 319));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        scrCliente.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setResizable(false);
            tblCliente.getColumnModel().getColumn(1).setResizable(false);
            tblCliente.getColumnModel().getColumn(2).setResizable(false);
            tblCliente.getColumnModel().getColumn(3).setResizable(false);
            tblCliente.getColumnModel().getColumn(4).setResizable(false);
            tblCliente.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.add(pnlTabla, "card3");

        pnlEditar.setAlignmentX(0.0F);
        pnlEditar.setAlignmentY(0.0F);
        pnlEditar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlEditar.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlEditar.setMinimumSize(new java.awt.Dimension(728, 360));

        imgRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        imgRegresar.setAlignmentY(0.0F);
        imgRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgRegresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        imgRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgRegresar.setMaximumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setMinimumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setPreferredSize(new java.awt.Dimension(67, 67));
        imgRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgRegresarMousePressed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblID.setText("ID");

        tbxID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxID.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNombre.setText("Nombre");

        tbxNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNumero.setText("Numero");

        tbxNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDireccion.setText("Direccion");

        tbxDireccion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDNI.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDNI.setText("DNI");

        tbxDNI.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEstado.setText("Estado");

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setAlignmentY(0.0F);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxNumero)
                            .addComponent(tbxID)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxDNI)
                            .addComponent(tbxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)))
                .addComponent(imgRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(tbxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDNI)
                            .addComponent(tbxDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlContenido.add(pnlEditar, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla() {
        List<Cliente> listaClientes = clienteController.listarClientes();

        DefaultTableModel model = (DefaultTableModel) tblCliente.getModel();
        model.setRowCount(0);

        for (Cliente cliente : listaClientes) {
            String estadoTexto = (cliente.getEstado() == 1) ? "Activo" : "Inactivo";
            Object[] rowData = {
                cliente.getId(),
                cliente.getNombre(),
                cliente.getNumero(),
                cliente.getDireccion(),
                cliente.getDni(),
                estadoTexto
            };
            model.addRow(rowData);
        }
    }    
    
    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        int selectedRow = tblCliente.getSelectedRow();
        if (selectedRow != -1) {
            // Obtén los datos de la fila seleccionada
            String id = tblCliente.getValueAt(selectedRow, 0).toString();
            String nombre = tblCliente.getValueAt(selectedRow, 1).toString();
            String numero = tblCliente.getValueAt(selectedRow, 2).toString();
            String direccion = tblCliente.getValueAt(selectedRow, 3).toString();
            String dni = tblCliente.getValueAt(selectedRow, 4).toString();
            String estado = tblCliente.getValueAt(selectedRow, 5).toString();

            // Muestra los datos en los JTextField y JComboBox correspondientes
            tbxID.setText(id);
            tbxNombre.setText(nombre);
            tbxNumero.setText(numero);
            tbxDireccion.setText(direccion);
            tbxDNI.setText(dni);
            cbxEstado.setSelectedItem(estado);
            
            // Cambia al panel de edición
            CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
            cardLayout.show(pnlContenido, "pnlEditar");
        }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void modificarCliente() {
        String idStr = tbxID.getText();
        int id = Integer.parseInt(idStr);
        
        String nombre = tbxNombre.getText();
        String numero = tbxNumero.getText();
        String direccion = tbxDireccion.getText();
        int dni = Integer.parseInt(tbxDNI.getText());
        int estado = cbxEstado.getSelectedItem().toString().equals("Activo") ? 1 : 0;

        Cliente clienteModificado = new Cliente();
        clienteModificado.setId(id);
        clienteModificado.setNombre(nombre);
        clienteModificado.setNumero(numero);
        clienteModificado.setDireccion(direccion);
        clienteModificado.setDni(dni);
        clienteModificado.setEstado(estado);

        clienteController.modificarCliente(clienteModificado);

        llenarTabla();
        JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.show(pnlContenido, "pnlTabla");
    }    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        modificarCliente();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void imgRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRegresarMousePressed
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.show(pnlContenido, "pnlTabla");
    }//GEN-LAST:event_imgRegresarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel imgRegresar;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scrCliente;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField tbxDNI;
    private javax.swing.JTextField tbxDireccion;
    private javax.swing.JTextField tbxID;
    private javax.swing.JTextField tbxNombre;
    private javax.swing.JTextField tbxNumero;
    // End of variables declaration//GEN-END:variables
}