/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.senati.proyecto.sistemapuntoventa.controller.CategoriaController;
import com.senati.proyecto.sistemapuntoventa.model.Producto;
import com.senati.proyecto.sistemapuntoventa.controller.ProductoController;
import com.senati.proyecto.sistemapuntoventa.model.Categoria;
import java.awt.CardLayout;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InterGestionarProducto extends javax.swing.JInternalFrame {
    
    private ProductoController productoController = new ProductoController();
    private CategoriaController categoriaController = new CategoriaController();
    
    public InterGestionarProducto() {
        initComponents();
        this.setSize(new Dimension(738,445));
        
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.addLayoutComponent(pnlTabla, "pnlTabla");
        cardLayout.addLayoutComponent(pnlEditar, "pnlEditar");
        
        llenarTabla();
        llenarComboBoxCategorias();
        
        tblProducto.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                tblProductoMouseClicked(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWallpaper = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        scrProducto = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        pnlEditar = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tbxID = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        tbxNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        scrDescripcion = new javax.swing.JScrollPane();
        tarDescripcion = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        imgRegresar = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        spnPrecio = new javax.swing.JSpinner();
        lblStock = new javax.swing.JLabel();
        spnStock = new javax.swing.JSpinner();
        btnActualizar = new javax.swing.JButton();

        lblWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        lblWallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.jpg"))); // NOI18N
        lblWallpaper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblWallpaper.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblWallpaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Producto");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setMaximumSize(new java.awt.Dimension(738, 445));
        setMinimumSize(new java.awt.Dimension(738, 445));
        setName(""); // NOI18N
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(738, 445));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        pnlTitulo.setBackground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setForeground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setAlignmentX(0.0F);
        pnlTitulo.setAlignmentY(0.0F);
        pnlTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTitulo.setMaximumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(728, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PRODUCTO");
        lblTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.setAlignmentX(0.0F);
        pnlContenido.setAlignmentY(0.0F);
        pnlContenido.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlContenido.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setPreferredSize(new java.awt.Dimension(728, 360));
        pnlContenido.setLayout(new java.awt.CardLayout());

        pnlTabla.setAlignmentX(0.0F);
        pnlTabla.setAlignmentY(0.0F);
        pnlTabla.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTabla.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setPreferredSize(new java.awt.Dimension(728, 360));

        scrProducto.setAlignmentX(0.0F);
        scrProducto.setAlignmentY(0.0F);
        scrProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrProducto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        scrProducto.setMaximumSize(new java.awt.Dimension(714, 319));
        scrProducto.setMinimumSize(new java.awt.Dimension(714, 319));
        scrProducto.setPreferredSize(new java.awt.Dimension(714, 319));

        tblProducto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Nombre", "Descripcion", "Precio", "Stock", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.setAlignmentX(0.0F);
        tblProducto.setAlignmentY(0.0F);
        tblProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblProducto.setEditingColumn(0);
        tblProducto.setEditingRow(0);
        tblProducto.setMaximumSize(new java.awt.Dimension(714, 319));
        tblProducto.setMinimumSize(new java.awt.Dimension(714, 319));
        tblProducto.setPreferredSize(new java.awt.Dimension(714, 319));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        scrProducto.setViewportView(tblProducto);
        if (tblProducto.getColumnModel().getColumnCount() > 0) {
            tblProducto.getColumnModel().getColumn(0).setResizable(false);
            tblProducto.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblProducto.getColumnModel().getColumn(1).setResizable(false);
            tblProducto.getColumnModel().getColumn(1).setPreferredWidth(35);
            tblProducto.getColumnModel().getColumn(2).setResizable(false);
            tblProducto.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblProducto.getColumnModel().getColumn(3).setResizable(false);
            tblProducto.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblProducto.getColumnModel().getColumn(4).setResizable(false);
            tblProducto.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblProducto.getColumnModel().getColumn(5).setResizable(false);
            tblProducto.getColumnModel().getColumn(5).setPreferredWidth(15);
            tblProducto.getColumnModel().getColumn(6).setResizable(false);
            tblProducto.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.add(pnlTabla, "card3");

        pnlEditar.setAlignmentX(0.0F);
        pnlEditar.setAlignmentY(0.0F);
        pnlEditar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlEditar.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlEditar.setMinimumSize(new java.awt.Dimension(728, 360));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblID.setText("ID");
        lblID.setAlignmentY(0.0F);

        tbxID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxID.setAlignmentX(0.0F);
        tbxID.setAlignmentY(0.0F);
        tbxID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxID.setEnabled(false);

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblCategoria.setText("Categoria");
        lblCategoria.setAlignmentY(0.0F);

        cbxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxCategoria.setAlignmentX(0.0F);
        cbxCategoria.setAlignmentY(0.0F);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNombre.setText("Nombre");
        lblNombre.setAlignmentY(0.0F);

        tbxNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxNombre.setAlignmentX(0.0F);
        tbxNombre.setAlignmentY(0.0F);
        tbxNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDescripcion.setText("Descripcion");
        lblDescripcion.setAlignmentY(0.0F);

        scrDescripcion.setAlignmentX(0.0F);
        scrDescripcion.setAlignmentY(0.0F);
        scrDescripcion.setAutoscrolls(true);
        scrDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        scrDescripcion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrDescripcion.setMaximumSize(new java.awt.Dimension(318, 100));
        scrDescripcion.setMinimumSize(new java.awt.Dimension(318, 100));
        scrDescripcion.setPreferredSize(new java.awt.Dimension(318, 100));

        tarDescripcion.setColumns(20);
        tarDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tarDescripcion.setRows(5);
        tarDescripcion.setAlignmentX(0.0F);
        tarDescripcion.setAlignmentY(0.0F);
        tarDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tarDescripcion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tarDescripcion.setMaximumSize(new java.awt.Dimension(318, 100));
        tarDescripcion.setMinimumSize(new java.awt.Dimension(318, 100));
        tarDescripcion.setPreferredSize(new java.awt.Dimension(306, 100));
        scrDescripcion.setViewportView(tarDescripcion);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEstado.setText("Estado");
        lblEstado.setAlignmentY(0.0F);

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbxEstado.setAlignmentX(0.0F);
        cbxEstado.setAlignmentY(0.0F);

        imgRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        imgRegresar.setAlignmentY(0.0F);
        imgRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgRegresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        imgRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgRegresar.setMaximumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setMinimumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setPreferredSize(new java.awt.Dimension(67, 67));
        imgRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgRegresarMousePressed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPrecio.setText("Precio");
        lblPrecio.setAlignmentY(0.0F);

        spnPrecio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        spnPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.01d));
        spnPrecio.setAlignmentX(0.0F);
        spnPrecio.setAlignmentY(0.0F);
        spnPrecio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblStock.setText("Stock");
        lblStock.setAlignmentY(0.0F);

        spnStock.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        spnStock.setModel(new javax.swing.SpinnerNumberModel());
        spnStock.setAlignmentX(0.0F);
        spnStock.setAlignmentY(0.0F);
        spnStock.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setAlignmentY(0.0F);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addGap(18, 18, 18)
                                .addComponent(scrDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(spnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditarLayout.createSequentialGroup()
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(imgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(imgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(20, 20, 20)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(scrDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPrecio)
                                .addComponent(lblStock)))
                        .addGap(20, 20, 20)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(174, 174, 174)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnlContenido.add(pnlEditar, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 726, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String obtenerNombreCategoria(int categoriaId) {
        List<Categoria> listaCategorias = categoriaController.listarCategorias();
        for (Categoria categoria : listaCategorias) {
            if (categoria.getId() == categoriaId) {
                return categoria.getNombre();
            }
        }
        return "Categoría Desconocida";
    }
    
    private void llenarTabla() {
        List<Producto> listaProductos = productoController.listarProductos();

        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.setRowCount(0);

        for (Producto producto : listaProductos) {
            String estadoTexto = (producto.getEstado() == 1) ? "Activo" : "Inactivo";
            String nombreCategoria = obtenerNombreCategoria(producto.getCategoria_id());
            
            Object[] rowData = {
                producto.getId(),
                nombreCategoria,
                producto.getNombre(),
                producto.getDescripcion(),
                producto.getPrecio(),
                producto.getStock(),
                estadoTexto
            };
            model.addRow(rowData);
        }
    }    
    
    private void llenarComboBoxCategorias() {
        List<Categoria> listaCategorias = categoriaController.listarCategorias();

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        for (Categoria categoria : listaCategorias) {
            comboBoxModel.addElement(categoria.getNombre());
        }
        cbxCategoria.setModel(comboBoxModel);
    }    
    
    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        //System.out.println("Hiciste clic en tblProducto");
        int selectedRow = tblProducto.getSelectedRow();
        if (selectedRow != -1) {
            // Obtén los datos de la fila seleccionada
            String id = tblProducto.getValueAt(selectedRow, 0).toString();
            String categoriaNombre = tblProducto.getValueAt(selectedRow, 1).toString();
            String nombre = tblProducto.getValueAt(selectedRow, 2).toString();
            String descripcion = tblProducto.getValueAt(selectedRow, 3).toString();
            String precio = tblProducto.getValueAt(selectedRow, 4).toString();
            String stock = tblProducto.getValueAt(selectedRow, 5).toString();
            String estado = tblProducto.getValueAt(selectedRow, 6).toString();
            //System.out.println("Obteniendo los datos de la fila seleccionada");

            // Muestra los datos en los Swing correspondientes
            tbxID.setText(id);
            cbxCategoria.setSelectedItem(categoriaNombre);
            tbxNombre.setText(nombre);
            tarDescripcion.setText(descripcion);
            spnPrecio.setValue(Double.parseDouble(precio));
            spnStock.setValue(Integer.parseInt(stock));
            cbxEstado.setSelectedItem(estado);
            //System.out.println("Mostrando los datos en los JTextField y JComboBox correspondientes");
            
            // Cambia al panel de edición
            CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
            cardLayout.show(pnlContenido, "pnlEditar");
            //System.out.println("Cambiando al panel de edición");
        }
    }//GEN-LAST:event_tblProductoMouseClicked

    private void modificarProducto() {
        try {
            String idStr = tbxID.getText();
            int id = Integer.parseInt(idStr);

            String nombre = tbxNombre.getText();
            String descripcion = tarDescripcion.getText();
            int estado = cbxEstado.getSelectedItem().toString().equals("Activo") ? 1 : 0;

            // Obtén el id de la categoría seleccionada en el JComboBox
            String categoriaNombre = cbxCategoria.getSelectedItem().toString();
            int categoriaId = -1;

            List<Categoria> listaCategorias = categoriaController.listarCategorias();
            for (Categoria categoria : listaCategorias) {
                if (categoria.getNombre().equals(categoriaNombre)) {
                    categoriaId = categoria.getId();
                    break;
                }
            }

            double precio = (double) spnPrecio.getValue();
            int stock = (int) spnStock.getValue();

            Producto productoModificado = new Producto();
            productoModificado.setId(id);
            productoModificado.setNombre(nombre);
            productoModificado.setDescripcion(descripcion);
            productoModificado.setEstado(estado);
            productoModificado.setCategoria_id(categoriaId);
            productoModificado.setPrecio(precio);
            productoModificado.setStock(stock);

            productoController.modificarProducto(productoModificado);

            llenarTabla();
            JOptionPane.showMessageDialog(this, "Producto actualizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
            cardLayout.show(pnlContenido, "pnlTabla");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa valores válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        modificarProducto();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void imgRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRegresarMousePressed
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.show(pnlContenido, "pnlTabla");
    }//GEN-LAST:event_imgRegresarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel imgRegresar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scrDescripcion;
    private javax.swing.JScrollPane scrProducto;
    private javax.swing.JSpinner spnPrecio;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextArea tarDescripcion;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField tbxID;
    private javax.swing.JTextField tbxNombre;
    // End of variables declaration//GEN-END:variables
}