/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.senati.proyecto.sistemapuntoventa.model.Categoria;
import com.senati.proyecto.sistemapuntoventa.controller.CategoriaController;
import java.awt.CardLayout;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InterGestionarCategoria extends javax.swing.JInternalFrame {
    
    private CategoriaController categoriaController = new CategoriaController();
    
    public InterGestionarCategoria() {
        initComponents();
        this.setSize(new Dimension(738,445));
        
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.addLayoutComponent(pnlTabla, "pnlTabla");
        cardLayout.addLayoutComponent(pnlEditar, "pnlEditar");
        
        llenarTabla();
        
        tblCategoria.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                tblCategoriaMouseClicked(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWallpaper = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        scrCategoria = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        pnlEditar = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tbxID = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        tbxNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        tbxDescripcion = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        imgRegresar = new javax.swing.JLabel();

        lblWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        lblWallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.jpg"))); // NOI18N
        lblWallpaper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblWallpaper.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblWallpaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Categoria");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setMaximumSize(new java.awt.Dimension(738, 445));
        setMinimumSize(new java.awt.Dimension(738, 445));
        setName(""); // NOI18N
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(738, 445));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        pnlTitulo.setBackground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setForeground(new java.awt.Color(230, 235, 239));
        pnlTitulo.setAlignmentX(0.0F);
        pnlTitulo.setAlignmentY(0.0F);
        pnlTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTitulo.setMaximumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(728, 50));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(728, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CATEGORIAS");
        lblTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.setAlignmentX(0.0F);
        pnlContenido.setAlignmentY(0.0F);
        pnlContenido.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlContenido.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlContenido.setLayout(new java.awt.CardLayout());

        pnlTabla.setAlignmentX(0.0F);
        pnlTabla.setAlignmentY(0.0F);
        pnlTabla.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlTabla.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setMinimumSize(new java.awt.Dimension(728, 360));
        pnlTabla.setPreferredSize(new java.awt.Dimension(728, 360));

        scrCategoria.setAlignmentX(0.0F);
        scrCategoria.setAlignmentY(0.0F);
        scrCategoria.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        scrCategoria.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        scrCategoria.setMaximumSize(new java.awt.Dimension(714, 319));
        scrCategoria.setMinimumSize(new java.awt.Dimension(714, 319));
        scrCategoria.setPreferredSize(new java.awt.Dimension(714, 319));

        tblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategoria.setAlignmentX(0.0F);
        tblCategoria.setAlignmentY(0.0F);
        tblCategoria.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblCategoria.setEditingColumn(0);
        tblCategoria.setEditingRow(0);
        tblCategoria.setMaximumSize(new java.awt.Dimension(714, 319));
        tblCategoria.setMinimumSize(new java.awt.Dimension(714, 319));
        tblCategoria.setPreferredSize(new java.awt.Dimension(714, 319));
        tblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaMouseClicked(evt);
            }
        });
        scrCategoria.setViewportView(tblCategoria);
        if (tblCategoria.getColumnModel().getColumnCount() > 0) {
            tblCategoria.getColumnModel().getColumn(0).setResizable(false);
            tblCategoria.getColumnModel().getColumn(1).setResizable(false);
            tblCategoria.getColumnModel().getColumn(2).setResizable(false);
            tblCategoria.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenido.add(pnlTabla, "card3");

        pnlEditar.setAlignmentX(0.0F);
        pnlEditar.setAlignmentY(0.0F);
        pnlEditar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlEditar.setMaximumSize(new java.awt.Dimension(728, 360));
        pnlEditar.setMinimumSize(new java.awt.Dimension(728, 360));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblID.setText("ID");
        lblID.setAlignmentY(0.0F);

        tbxID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxID.setAlignmentX(0.0F);
        tbxID.setAlignmentY(0.0F);
        tbxID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxID.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNombre.setText("Nombre");
        lblNombre.setAlignmentY(0.0F);

        tbxNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxNombre.setAlignmentX(0.0F);
        tbxNombre.setAlignmentY(0.0F);
        tbxNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDescripcion.setText("Descripcion");
        lblDescripcion.setAlignmentY(0.0F);

        tbxDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxDescripcion.setAlignmentX(0.0F);
        tbxDescripcion.setAlignmentY(0.0F);
        tbxDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEstado.setText("Estado");
        lblEstado.setAlignmentY(0.0F);

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbxEstado.setAlignmentX(0.0F);
        cbxEstado.setAlignmentY(0.0F);

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setAlignmentY(0.0F);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        imgRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        imgRegresar.setAlignmentY(0.0F);
        imgRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgRegresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        imgRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgRegresar.setMaximumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setMinimumSize(new java.awt.Dimension(67, 67));
        imgRegresar.setPreferredSize(new java.awt.Dimension(67, 67));
        imgRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgRegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbxDescripcion)
                    .addComponent(tbxID)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxNombre))
                .addGap(119, 119, 119)
                .addComponent(imgRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(20, 20, 20))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addComponent(imgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(tbxDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pnlContenido.add(pnlEditar, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla() {
        List<Categoria> listaCategorias = categoriaController.listarCategorias();

        DefaultTableModel model = (DefaultTableModel) tblCategoria.getModel();
        model.setRowCount(0);

        for (Categoria categoria : listaCategorias) {
            String estadoTexto = (categoria.getEstado() == 1) ? "Activo" : "Inactivo";
            Object[] rowData = {
                categoria.getId(),
                categoria.getNombre(),
                categoria.getDescripcion(),
                estadoTexto
            };
            model.addRow(rowData);
        }
    }    
    
    private void tblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaMouseClicked
        int selectedRow = tblCategoria.getSelectedRow();
        if (selectedRow != -1) {
            // Obtén los datos de la fila seleccionada
            String id = tblCategoria.getValueAt(selectedRow, 0).toString();
            String nombre = tblCategoria.getValueAt(selectedRow, 1).toString();
            String descripcion = tblCategoria.getValueAt(selectedRow, 2).toString();
            String estado = tblCategoria.getValueAt(selectedRow, 3).toString();

            // Muestra los datos en los JTextField y JComboBox correspondientes
            tbxID.setText(id);
            tbxNombre.setText(nombre);
            tbxDescripcion.setText(descripcion);
            cbxEstado.setSelectedItem(estado);
            
            // Cambia al panel de edición
            CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
            cardLayout.show(pnlContenido, "pnlEditar");
        }
    }//GEN-LAST:event_tblCategoriaMouseClicked

    private void modificarCategoria() {
        String idStr = tbxID.getText();
        int id = Integer.parseInt(idStr);
        
        String nombre = tbxNombre.getText();
        String descripcion = tbxDescripcion.getText();
        int estado = cbxEstado.getSelectedItem().toString().equals("Activo") ? 1 : 0;

        Categoria categoriaModificado = new Categoria();
        categoriaModificado.setId(id);
        categoriaModificado.setNombre(nombre);
        categoriaModificado.setDescripcion(descripcion);
        categoriaModificado.setEstado(estado);

        categoriaController.modificarCategoria(categoriaModificado);

        llenarTabla();
        JOptionPane.showMessageDialog(this, "Categoria actualizada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.show(pnlContenido, "pnlTabla");
    }    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        modificarCategoria();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void imgRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRegresarMousePressed
        CardLayout cardLayout = (CardLayout) pnlContenido.getLayout();
        cardLayout.show(pnlContenido, "pnlTabla");
    }//GEN-LAST:event_imgRegresarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel imgRegresar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scrCategoria;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTextField tbxDescripcion;
    private javax.swing.JTextField tbxID;
    private javax.swing.JTextField tbxNombre;
    // End of variables declaration//GEN-END:variables
}