/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senati.proyecto.sistemapuntoventa.view;

import com.senati.proyecto.sistemapuntoventa.model.Cliente;
import com.senati.proyecto.sistemapuntoventa.model.Usuario;
import com.senati.proyecto.sistemapuntoventa.model.Producto;
import com.senati.proyecto.sistemapuntoventa.model.Venta;
import com.senati.proyecto.sistemapuntoventa.model.DetalleVenta;

import com.senati.proyecto.sistemapuntoventa.controller.ClienteController;
import com.senati.proyecto.sistemapuntoventa.controller.UsuarioController;
import com.senati.proyecto.sistemapuntoventa.controller.ProductoController;
import com.senati.proyecto.sistemapuntoventa.controller.VentaController;
import com.senati.proyecto.sistemapuntoventa.controller.DetalleVentaController;
import static com.senati.proyecto.sistemapuntoventa.view.FrmMenu.jDesktopPane;

import java.awt.Dimension;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InterVenta extends javax.swing.JInternalFrame {
    private ClienteController clienteController = new ClienteController();
    private UsuarioController usuarioController = new UsuarioController();
    private ProductoController productoController = new ProductoController();
    private VentaController ventaController = new VentaController();
    private DetalleVentaController detalleventaController = new DetalleVentaController();
    
    private final int usuarioId;
    private int ventaId;

    public InterVenta(int usuarioId) {
        this.usuarioId = usuarioId;
        initComponents();
        this.setSize(new Dimension(863,795));
        
        llenarTBXFecha();
        llenarTBXNFactura();
        llenarTBXVendedor();
        llenarCBXProducto();

        /*
        tblProducto.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tblProducto.getSelectionModel().getLeadSelectionIndex();
                    if (selectedRow != -1) {
                        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
                        model.removeRow(selectedRow);
                        
                        calcularPrecio();
                    }
                }
            }
        });
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        tbxBuscarCodigo = new javax.swing.JTextField();
        btnBuscarCodigo = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        tbxCodigo = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        tbxCliente = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        tbxNumero = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        tbxDireccion = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        tbxDNI = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        tbxFecha = new javax.swing.JTextField();
        lblNFactura = new javax.swing.JLabel();
        tbxNFactura = new javax.swing.JTextField();
        lblFormaPago = new javax.swing.JLabel();
        cbxFormaPago = new javax.swing.JComboBox<>();
        lblVendedor = new javax.swing.JLabel();
        tbxVendedor = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        tbxCantidad = new javax.swing.JTextField();
        btnAñadirProducto = new javax.swing.JButton();
        pnlProducto = new javax.swing.JPanel();
        scrProducto = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        lblEfectivo = new javax.swing.JLabel();
        tbxEfectivo = new javax.swing.JTextField();
        lblNetoPagar = new javax.swing.JLabel();
        tbxNetoPagar = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        tbxCambio = new javax.swing.JTextField();
        btnCalcularCambio = new javax.swing.JButton();
        lblDescuento = new javax.swing.JLabel();
        tbxDescuento = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        tbxSubtotal = new javax.swing.JTextField();
        lblIGV = new javax.swing.JLabel();
        tbxIGV = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        tbxMontoTotal = new javax.swing.JTextField();
        pnlAccines = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Facturiacion");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setMaximumSize(new java.awt.Dimension(863, 795));
        setMinimumSize(new java.awt.Dimension(863, 795));
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(863, 795));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Facturación");
        lblTitulo.setAlignmentY(0.0F);
        lblTitulo.setAutoscrolls(true);
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setMaximumSize(new java.awt.Dimension(832, 30));
        lblTitulo.setMinimumSize(new java.awt.Dimension(832, 30));
        lblTitulo.setPreferredSize(new java.awt.Dimension(832, 30));

        pnlDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDatos.setAlignmentX(0.0F);
        pnlDatos.setAlignmentY(0.0F);
        pnlDatos.setMaximumSize(new java.awt.Dimension(832, 224));
        pnlDatos.setMinimumSize(new java.awt.Dimension(832, 224));

        tbxBuscarCodigo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxBuscarCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxBuscarCodigo.setAlignmentX(0.0F);
        tbxBuscarCodigo.setAlignmentY(0.0F);
        tbxBuscarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxBuscarCodigo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxBuscarCodigo.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxBuscarCodigo.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxBuscarCodigo.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxBuscarCodigo.setPreferredSize(new java.awt.Dimension(200, 25));

        btnBuscarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBuscarCodigo.setText("Buscar Codigo");
        btnBuscarCodigo.setAlignmentY(0.0F);
        btnBuscarCodigo.setAutoscrolls(true);
        btnBuscarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCodigo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnBuscarCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setText("Codigo:");
        lblCodigo.setAlignmentY(0.0F);
        lblCodigo.setAutoscrolls(true);
        lblCodigo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxCodigo.setEditable(false);
        tbxCodigo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxCodigo.setAlignmentX(0.0F);
        tbxCodigo.setAlignmentY(0.0F);
        tbxCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxCodigo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxCodigo.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxCodigo.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxCodigo.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxCodigo.setPreferredSize(new java.awt.Dimension(200, 25));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCliente.setText("Cliente:");
        lblCliente.setAlignmentY(0.0F);
        lblCliente.setAutoscrolls(true);
        lblCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxCliente.setEditable(false);
        tbxCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxCliente.setAlignmentX(0.0F);
        tbxCliente.setAlignmentY(0.0F);
        tbxCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxCliente.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxCliente.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxCliente.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxCliente.setPreferredSize(new java.awt.Dimension(200, 25));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumero.setText("Numero:");
        lblNumero.setAlignmentY(0.0F);
        lblNumero.setAutoscrolls(true);
        lblNumero.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxNumero.setEditable(false);
        tbxNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxNumero.setAlignmentX(0.0F);
        tbxNumero.setAlignmentY(0.0F);
        tbxNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxNumero.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxNumero.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxNumero.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxNumero.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxNumero.setPreferredSize(new java.awt.Dimension(200, 25));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion.setText("Direccion:");
        lblDireccion.setAlignmentY(0.0F);
        lblDireccion.setAutoscrolls(true);
        lblDireccion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblDireccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxDireccion.setEditable(false);
        tbxDireccion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxDireccion.setAlignmentX(0.0F);
        tbxDireccion.setAlignmentY(0.0F);
        tbxDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxDireccion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxDireccion.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxDireccion.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxDireccion.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxDireccion.setPreferredSize(new java.awt.Dimension(200, 25));

        lblDNI.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDNI.setText("DNI:");
        lblDNI.setAlignmentY(0.0F);
        lblDNI.setAutoscrolls(true);
        lblDNI.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblDNI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxDNI.setEditable(false);
        tbxDNI.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxDNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxDNI.setAlignmentX(0.0F);
        tbxDNI.setAlignmentY(0.0F);
        tbxDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxDNI.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxDNI.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxDNI.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxDNI.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxDNI.setPreferredSize(new java.awt.Dimension(200, 25));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha.setText("Fecha:");
        lblFecha.setAlignmentY(0.0F);
        lblFecha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxFecha.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxFecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxFecha.setAlignmentX(0.0F);
        tbxFecha.setAlignmentY(0.0F);
        tbxFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxFecha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxFecha.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxFecha.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxFecha.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxFecha.setPreferredSize(new java.awt.Dimension(200, 25));

        lblNFactura.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNFactura.setText("N de Factura:");
        lblNFactura.setAlignmentY(0.0F);
        lblNFactura.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblNFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxNFactura.setEditable(false);
        tbxNFactura.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNFactura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxNFactura.setAlignmentX(0.0F);
        tbxNFactura.setAlignmentY(0.0F);
        tbxNFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxNFactura.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxNFactura.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxNFactura.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxNFactura.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxNFactura.setPreferredSize(new java.awt.Dimension(200, 25));

        lblFormaPago.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblFormaPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFormaPago.setText("Forma de Pago:");
        lblFormaPago.setAlignmentY(0.0F);
        lblFormaPago.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblFormaPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbxFormaPago.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxFormaPago.setMaximumRowCount(2);
        cbxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credito", "Devito" }));
        cbxFormaPago.setAlignmentX(0.0F);
        cbxFormaPago.setAlignmentY(0.0F);
        cbxFormaPago.setAutoscrolls(true);
        cbxFormaPago.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxFormaPago.setMaximumSize(new java.awt.Dimension(200, 25));
        cbxFormaPago.setMinimumSize(new java.awt.Dimension(200, 25));
        cbxFormaPago.setPreferredSize(new java.awt.Dimension(200, 25));

        lblVendedor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblVendedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVendedor.setText("Vendedor:");
        lblVendedor.setAlignmentY(0.0F);
        lblVendedor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbxVendedor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxVendedor.setAlignmentX(0.0F);
        tbxVendedor.setAlignmentY(0.0F);
        tbxVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxVendedor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxVendedor.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxVendedor.setMaximumSize(new java.awt.Dimension(200, 25));
        tbxVendedor.setMinimumSize(new java.awt.Dimension(200, 25));
        tbxVendedor.setPreferredSize(new java.awt.Dimension(200, 25));

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbxBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbxCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(tbxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(tbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbxNFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFormaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProducto.setText("Producto:");
        lblProducto.setAlignmentY(0.0F);
        lblProducto.setAutoscrolls(true);
        lblProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        cbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Producto" }));
        cbxProducto.setAlignmentX(0.0F);
        cbxProducto.setAlignmentY(0.0F);
        cbxProducto.setAutoscrolls(true);
        cbxProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidad.setText("Cantidad:");
        lblCantidad.setAlignmentY(0.0F);
        lblCantidad.setAutoscrolls(true);
        lblCantidad.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tbxCantidad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxCantidad.setAlignmentX(0.0F);
        tbxCantidad.setAlignmentY(0.0F);
        tbxCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxCantidad.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxCantidad.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxCantidad.setMaximumSize(new java.awt.Dimension(80, 30));
        tbxCantidad.setMinimumSize(new java.awt.Dimension(80, 30));
        tbxCantidad.setPreferredSize(new java.awt.Dimension(80, 30));

        btnAñadirProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAñadirProducto.setText("Añadir Productos");
        btnAñadirProducto.setAlignmentY(0.0F);
        btnAñadirProducto.setAutoscrolls(true);
        btnAñadirProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadirProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAñadirProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAñadirProducto.setMaximumSize(new java.awt.Dimension(200, 30));
        btnAñadirProducto.setMinimumSize(new java.awt.Dimension(200, 30));
        btnAñadirProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProductoActionPerformed(evt);
            }
        });

        pnlProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlProducto.setMaximumSize(new java.awt.Dimension(764, 234));
        pnlProducto.setMinimumSize(new java.awt.Dimension(764, 234));

        scrProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrProducto.setMaximumSize(new java.awt.Dimension(740, 210));
        scrProducto.setMinimumSize(new java.awt.Dimension(740, 210));
        scrProducto.setPreferredSize(new java.awt.Dimension(740, 210));

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Descuento", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.setAlignmentX(0.0F);
        tblProducto.setAlignmentY(0.0F);
        tblProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProducto.setMaximumSize(new java.awt.Dimension(740, 210));
        tblProducto.setMinimumSize(new java.awt.Dimension(740, 210));
        tblProducto.setPreferredSize(new java.awt.Dimension(740, 210));
        scrProducto.setViewportView(tblProducto);
        if (tblProducto.getColumnModel().getColumnCount() > 0) {
            tblProducto.getColumnModel().getColumn(0).setResizable(false);
            tblProducto.getColumnModel().getColumn(1).setResizable(false);
            tblProducto.getColumnModel().getColumn(2).setResizable(false);
            tblProducto.getColumnModel().getColumn(3).setResizable(false);
            tblProducto.getColumnModel().getColumn(4).setResizable(false);
        }

        lblEfectivo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEfectivo.setText("Pagó con:");
        lblEfectivo.setAlignmentY(0.0F);
        lblEfectivo.setAutoscrolls(true);
        lblEfectivo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEfectivo.setMaximumSize(new java.awt.Dimension(102, 25));
        lblEfectivo.setMinimumSize(new java.awt.Dimension(102, 25));
        lblEfectivo.setPreferredSize(new java.awt.Dimension(102, 25));

        tbxEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxEfectivo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxEfectivo.setAlignmentX(0.0F);
        tbxEfectivo.setAlignmentY(0.0F);
        tbxEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxEfectivo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxEfectivo.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxEfectivo.setMaximumSize(new java.awt.Dimension(150, 25));
        tbxEfectivo.setMinimumSize(new java.awt.Dimension(150, 25));
        tbxEfectivo.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNetoPagar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNetoPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNetoPagar.setText("Neto a Pagar:");
        lblNetoPagar.setAlignmentY(0.0F);
        lblNetoPagar.setAutoscrolls(true);
        lblNetoPagar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblNetoPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNetoPagar.setMaximumSize(new java.awt.Dimension(102, 25));
        lblNetoPagar.setMinimumSize(new java.awt.Dimension(102, 25));
        lblNetoPagar.setPreferredSize(new java.awt.Dimension(102, 25));

        tbxNetoPagar.setEditable(false);
        tbxNetoPagar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxNetoPagar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxNetoPagar.setAlignmentX(0.0F);
        tbxNetoPagar.setAlignmentY(0.0F);
        tbxNetoPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxNetoPagar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxNetoPagar.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxNetoPagar.setMaximumSize(new java.awt.Dimension(150, 25));
        tbxNetoPagar.setMinimumSize(new java.awt.Dimension(150, 25));
        tbxNetoPagar.setPreferredSize(new java.awt.Dimension(150, 25));

        lblCambio.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCambio.setText("Devolver:");
        lblCambio.setAlignmentY(0.0F);
        lblCambio.setAutoscrolls(true);
        lblCambio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblCambio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCambio.setMaximumSize(new java.awt.Dimension(102, 25));
        lblCambio.setMinimumSize(new java.awt.Dimension(102, 25));
        lblCambio.setPreferredSize(new java.awt.Dimension(102, 25));

        tbxCambio.setEditable(false);
        tbxCambio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbxCambio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxCambio.setAlignmentX(0.0F);
        tbxCambio.setAlignmentY(0.0F);
        tbxCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxCambio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxCambio.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxCambio.setMaximumSize(new java.awt.Dimension(150, 25));
        tbxCambio.setMinimumSize(new java.awt.Dimension(150, 25));
        tbxCambio.setPreferredSize(new java.awt.Dimension(150, 25));

        btnCalcularCambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcularCambio.setText("Calcular Cambio");
        btnCalcularCambio.setAlignmentY(0.0F);
        btnCalcularCambio.setAutoscrolls(true);
        btnCalcularCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularCambio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCalcularCambio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcularCambio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCalcularCambio.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCalcularCambio.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCalcularCambio.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCalcularCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCambioActionPerformed(evt);
            }
        });

        lblDescuento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescuento.setText("Descuento:");
        lblDescuento.setAlignmentY(0.0F);
        lblDescuento.setAutoscrolls(true);
        lblDescuento.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblDescuento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDescuento.setMaximumSize(new java.awt.Dimension(89, 20));
        lblDescuento.setMinimumSize(new java.awt.Dimension(89, 20));
        lblDescuento.setPreferredSize(new java.awt.Dimension(89, 20));

        tbxDescuento.setEditable(false);
        tbxDescuento.setBackground(new java.awt.Color(0, 0, 0));
        tbxDescuento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbxDescuento.setForeground(new java.awt.Color(0, 153, 0));
        tbxDescuento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxDescuento.setAlignmentX(0.0F);
        tbxDescuento.setAlignmentY(0.0F);
        tbxDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxDescuento.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxDescuento.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxDescuento.setMaximumSize(new java.awt.Dimension(130, 20));
        tbxDescuento.setMinimumSize(new java.awt.Dimension(130, 20));
        tbxDescuento.setPreferredSize(new java.awt.Dimension(130, 20));

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setText("SubTotal:");
        lblSubtotal.setAlignmentY(0.0F);
        lblSubtotal.setAutoscrolls(true);
        lblSubtotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblSubtotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubtotal.setMaximumSize(new java.awt.Dimension(89, 20));
        lblSubtotal.setMinimumSize(new java.awt.Dimension(89, 20));
        lblSubtotal.setPreferredSize(new java.awt.Dimension(89, 20));

        tbxSubtotal.setEditable(false);
        tbxSubtotal.setBackground(new java.awt.Color(0, 0, 0));
        tbxSubtotal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbxSubtotal.setForeground(new java.awt.Color(0, 153, 0));
        tbxSubtotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxSubtotal.setAlignmentX(0.0F);
        tbxSubtotal.setAlignmentY(0.0F);
        tbxSubtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxSubtotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxSubtotal.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxSubtotal.setMaximumSize(new java.awt.Dimension(130, 20));
        tbxSubtotal.setMinimumSize(new java.awt.Dimension(130, 20));
        tbxSubtotal.setPreferredSize(new java.awt.Dimension(130, 20));

        lblIGV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblIGV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIGV.setText("IGV:");
        lblIGV.setAlignmentY(0.0F);
        lblIGV.setAutoscrolls(true);
        lblIGV.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblIGV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIGV.setMaximumSize(new java.awt.Dimension(89, 20));
        lblIGV.setMinimumSize(new java.awt.Dimension(89, 20));
        lblIGV.setPreferredSize(new java.awt.Dimension(89, 20));

        tbxIGV.setEditable(false);
        tbxIGV.setBackground(new java.awt.Color(0, 0, 0));
        tbxIGV.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbxIGV.setForeground(new java.awt.Color(0, 153, 0));
        tbxIGV.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxIGV.setAlignmentX(0.0F);
        tbxIGV.setAlignmentY(0.0F);
        tbxIGV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxIGV.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxIGV.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxIGV.setMaximumSize(new java.awt.Dimension(130, 20));
        tbxIGV.setMinimumSize(new java.awt.Dimension(130, 20));
        tbxIGV.setPreferredSize(new java.awt.Dimension(130, 20));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("Neto a Pagar:");
        lblTotal.setAlignmentY(0.0F);
        lblTotal.setAutoscrolls(true);
        lblTotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTotal.setMaximumSize(new java.awt.Dimension(89, 20));
        lblTotal.setMinimumSize(new java.awt.Dimension(89, 20));
        lblTotal.setPreferredSize(new java.awt.Dimension(89, 20));

        tbxMontoTotal.setEditable(false);
        tbxMontoTotal.setBackground(new java.awt.Color(0, 0, 0));
        tbxMontoTotal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbxMontoTotal.setForeground(new java.awt.Color(0, 153, 0));
        tbxMontoTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tbxMontoTotal.setAlignmentX(0.0F);
        tbxMontoTotal.setAlignmentY(0.0F);
        tbxMontoTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbxMontoTotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbxMontoTotal.setMargin(new java.awt.Insets(0, 5, 0, 5));
        tbxMontoTotal.setMaximumSize(new java.awt.Dimension(130, 20));
        tbxMontoTotal.setMinimumSize(new java.awt.Dimension(130, 20));
        tbxMontoTotal.setPreferredSize(new java.awt.Dimension(130, 20));

        pnlAccines.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCobrar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salario.png"))); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.setAlignmentY(0.0F);
        btnCobrar.setAutoscrolls(true);
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCobrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCobrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCobrar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCobrar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCobrar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        btnNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/objetivo.png"))); // NOI18N
        btnNuevoCliente.setText("Nuevo C.");
        btnNuevoCliente.setAlignmentY(0.0F);
        btnNuevoCliente.setAutoscrolls(true);
        btnNuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnNuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevoCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNuevoCliente.setMaximumSize(new java.awt.Dimension(100, 30));
        btnNuevoCliente.setMinimumSize(new java.awt.Dimension(100, 30));
        btnNuevoCliente.setPreferredSize(new java.awt.Dimension(100, 30));
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setAlignmentY(0.0F);
        btnImprimir.setAutoscrolls(true);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnImprimir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnImprimir.setMaximumSize(new java.awt.Dimension(100, 30));
        btnImprimir.setMinimumSize(new java.awt.Dimension(100, 30));
        btnImprimir.setPreferredSize(new java.awt.Dimension(100, 30));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentY(0.0F);
        btnCancelar.setAutoscrolls(true);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccinesLayout = new javax.swing.GroupLayout(pnlAccines);
        pnlAccines.setLayout(pnlAccinesLayout);
        pnlAccinesLayout.setHorizontalGroup(
            pnlAccinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccinesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlAccinesLayout.setVerticalGroup(
            pnlAccinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccinesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlAccinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                        .addComponent(pnlAccines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(tbxEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblNetoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbxCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalcularCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxNetoPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxMontoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxIGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scrProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxNetoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNetoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(pnlAccines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblProducto)
                        .addGap(10, 10, 10)
                        .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblCantidad)
                        .addGap(10, 10, 10)
                        .addComponent(tbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnAñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // --BUSCAR CLIENTE-
    private void buscarCliente() {
        try {
            int codigoBuscado = Integer.parseInt(tbxBuscarCodigo.getText());
    
            List<Cliente> listaClientes = clienteController.listarClientes();
    
            // Busca el cliente por su código en la lista
            Cliente clienteEncontrado = null;
            for (Cliente cliente : listaClientes) {
                if (cliente.getId() == codigoBuscado) {
                    clienteEncontrado = cliente;
                    break;
                }
            }
    
            if (clienteEncontrado != null) {
                if (clienteEncontrado.getEstado() == 1) {
                    // Llena los campos con los datos del cliente encontrado
                    tbxCodigo.setText(String.valueOf(clienteEncontrado.getId()));
                    tbxCliente.setText(clienteEncontrado.getNombre());
                    tbxNumero.setText(clienteEncontrado.getNumero());
                    tbxDireccion.setText(clienteEncontrado.getDireccion());
                    tbxDNI.setText(String.valueOf(clienteEncontrado.getDni()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente deshabilitado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cliente no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa un código válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        buscarCliente();
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    // -LLENAR FECHA-
    private void llenarTBXFecha() {
        Date fechaActual = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        tbxFecha.setText(formatoFecha.format(fechaActual));
    }
    
    // -LLENAR N° DE FACTURA
    private void llenarTBXNFactura() {
        List<Venta> listaVentas = ventaController.listarVentas();

        if (!listaVentas.isEmpty()) {
            Venta ultimaVenta = listaVentas.get(listaVentas.size() - 1);
            int ultimoId = ultimaVenta.getId() + 1;
            tbxNFactura.setText(String.valueOf(ultimoId));
        } else {
            tbxNFactura.setText("1");
        }
    }
    
    // -LLENAR VENDEDOR-
    private String obtenerUsuarioPorId(int usuarioId) {
        List<Usuario> listaUsuarios = usuarioController.listarUsuarios();
        for (Usuario usuario : listaUsuarios) {
            if (usuario.getId() == usuarioId) {
                return usuario.getNombre();
            }
        }
        return "Usuario Desconocido";
    }
    
    private void llenarTBXVendedor() {
        String nombreUsuario = obtenerUsuarioPorId(usuarioId);
        tbxVendedor.setText(nombreUsuario);
    }

    // -LLENAR PRODUCTO-
    private void llenarCBXProducto() {
        List<Producto> listaProductos = productoController.listarProductos();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (Producto producto : listaProductos) {
            if (producto.getEstado() == 1) {
                model.addElement(producto.getNombre());
            }
        }
        cbxProducto.setModel(model);
    }
    
    private double calcularDescuento(int cantidad, double precioUnitario) {
        double descuento = 0.0;

        if (cantidad >= 55) {
            descuento = 0.20 * precioUnitario*cantidad; // 20%
        } else if (cantidad >= 40) {
            descuento = 0.15 * precioUnitario*cantidad; // 15%
        } else if (cantidad >= 25) {
            descuento = 0.10 * precioUnitario*cantidad; // 10%
        } else if (cantidad >= 10) {
            descuento = 0.05 * precioUnitario*cantidad; // 5%
        }

        return descuento;
    }

    private void llenarTBLProducto() {
        try {
            String nombreSeleccionado = (String) cbxProducto.getSelectedItem();

            if (nombreSeleccionado != null) {
                List<Producto> listaProducto = productoController.listarProductos();

                DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();

                boolean productoEncontrado = false;
                int filaExistente = -1;

                for (int i = 0; i < model.getRowCount(); i++) {
                    String nombreTabla = (String) model.getValueAt(i, 0);
                    if (nombreTabla.equals(nombreSeleccionado)) {
                        productoEncontrado = true;
                        filaExistente = i;
                        break;
                    }
                }

                int cantidad = Integer.parseInt(tbxCantidad.getText());

                for (Producto producto : listaProducto) {
                    if (producto.getNombre().equals(nombreSeleccionado)) {
                        double total = producto.getPrecio() * cantidad;
                        double descuento = calcularDescuento(cantidad, producto.getPrecio());

                        if (productoEncontrado) {
                            model.setValueAt(cantidad, filaExistente, 2);
                            model.setValueAt(descuento, filaExistente, 3);
                            model.setValueAt(total - descuento, filaExistente, 4);
                        } else {
                            Object[] rowData = {
                                producto.getNombre(),
                                producto.getPrecio(),
                                cantidad,
                                descuento,
                                total - descuento
                            };
                            model.addRow(rowData);
                        }
                        break;
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa un valor válido para la cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de productos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // -CALCULAR PRECIO-
    private void calcularPrecio() {
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        
        double totalDescuento = 0;
        double subtotal = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            totalDescuento += (Double) model.getValueAt(i, 3); // Asumiendo que la columna 3 contiene los descuentos
            subtotal += (Double) model.getValueAt(i, 4); // Asumiendo que la columna 4 contiene los subtotales
        }

        double igv = 0.18 * subtotal;
        double montoTotal = subtotal + igv;

        DecimalFormat df = new DecimalFormat("#.##");
        totalDescuento = Double.parseDouble(df.format(totalDescuento));
        subtotal = Double.parseDouble(df.format(subtotal));
        igv = Double.parseDouble(df.format(igv));
        montoTotal = Double.parseDouble(df.format(montoTotal));

        tbxDescuento.setText(String.valueOf(totalDescuento));
        tbxSubtotal.setText(String.valueOf(subtotal));
        tbxIGV.setText(String.valueOf(igv));
        tbxMontoTotal.setText(String.valueOf(montoTotal));
        tbxNetoPagar.setText(String.valueOf("S/. "+montoTotal));
    }
    
    private void btnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProductoActionPerformed
        llenarTBLProducto();
        calcularPrecio();
    }//GEN-LAST:event_btnAñadirProductoActionPerformed

    private void calcularCambio() {
        double montoTotal, efectivo, cambio;
        
        montoTotal = Double.parseDouble(tbxMontoTotal.getText());
        efectivo = Double.parseDouble(tbxEfectivo.getText());
        cambio = efectivo - montoTotal;
        
        DecimalFormat df = new DecimalFormat("#.##");
        cambio = Double.parseDouble(df.format(cambio));
        
        tbxCambio.setText(String.valueOf("S/. "+cambio));
    }

    private void btnCalcularCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCambioActionPerformed
        calcularCambio();
    }//GEN-LAST:event_btnCalcularCambioActionPerformed
    
    // -REGISTAR VENTA-
    private int registrarVenta() {
        String nombreCliente = (String) tbxCliente.getText();
    
        Cliente clienteSeleccionado = null;
        for (Cliente cliente : clienteController.listarClientes()) {
            if (cliente.getNombre().equals(nombreCliente)) {
                clienteSeleccionado = cliente;
                break;
            }
        }
        if (clienteSeleccionado != null) {
            int usuario_id = usuarioId;
            int cliente_id = clienteSeleccionado.getId();
    
            Timestamp fecha_venta = new Timestamp(System.currentTimeMillis());
            double descuento = Double.parseDouble(tbxDescuento.getText());
            double subtotal = Double.parseDouble(tbxSubtotal.getText());
            double igv = Double.parseDouble(tbxIGV.getText());
            double cantidad_total = Double.parseDouble(tbxMontoTotal.getText());
    
            Venta nuevaVenta = new Venta();
            nuevaVenta.setUsuario_id(usuario_id);
            nuevaVenta.setCliente_id(cliente_id);
            nuevaVenta.setFecha_venta(fecha_venta);
            nuevaVenta.setDescuento(descuento);
            nuevaVenta.setSubtotal(subtotal);
            nuevaVenta.setIgv(igv);
            nuevaVenta.setCantidad_total(cantidad_total);
    
            int ventaId = ventaController.agregarVenta(nuevaVenta);
    
            if (ventaId != -1) {
                this.ventaId = ventaId;
                JOptionPane.showMessageDialog(this, "Venta registrada exitosamente. N° de Venta: " + ventaId, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la venta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            // Devuelve el ID de la venta registrada
            return ventaId;
        } else {
            JOptionPane.showMessageDialog(this, "Error: Cliente no seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            // Devuelve -1 para indicar un error
            return -1;
        }
    }
    
    private void registrarDetalleVenta(int ventaId) {
        try {
            DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
    
            for (int i = 0; i < model.getRowCount(); i++) {
                String nombreProducto = (String) model.getValueAt(i, 0);
                double precio_unitario = Double.parseDouble(model.getValueAt(i, 1).toString());
                int cantidad = Integer.parseInt(model.getValueAt(i, 2).toString());
                double descuento = Double.parseDouble(model.getValueAt(i, 3).toString());
                double precio_total = Double.parseDouble(model.getValueAt(i, 4).toString());
    
                int producto_id = -1;
                List<Producto> listaProductos = productoController.listarProductos();
                for (Producto producto : listaProductos) {
                    if (producto.getNombre().equals(nombreProducto)) {
                        producto_id = producto.getId();
                        break;
                    }
                }
    
                if (producto_id != -1) {
                    DetalleVenta nuevoDetalleVenta = new DetalleVenta();
                    nuevoDetalleVenta.setVenta_id(ventaId);
                    nuevoDetalleVenta.setProducto_id(producto_id);
                    nuevoDetalleVenta.setPrecio_unitario(precio_unitario);
                    nuevoDetalleVenta.setCantidad(cantidad);
                    nuevoDetalleVenta.setDescuento(descuento);
                    nuevoDetalleVenta.setPrecio_total(precio_total);
    
                    detalleventaController.agregarDetalleVenta(nuevoDetalleVenta);
                } else {
                    System.out.println("Error: Producto no encontrado - " + nombreProducto);
                }
            }
            //JOptionPane.showMessageDialog(this, "Detalle de venta registrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al registrar los detalles de la venta.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        int ventaId = registrarVenta();
        try {
            registrarDetalleVenta(ventaId);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error al registrar la venta:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    // -NUEVO CLIENTE-
    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        InterNuevoCliente interCliente = new InterNuevoCliente();
        jDesktopPane.add(interCliente);
        interCliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    // -IMPRIMIR VENTA-

    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    // -CANCELAR VENTA-
    private void vaciarVenta() {
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.setRowCount(0);
        tbxCantidad.setText("");
        tbxEfectivo.setText("");
        tbxCambio.setText("");
        tbxNetoPagar.setText("");
        tbxDescuento.setText("");
        tbxSubtotal.setText("");
        tbxIGV.setText("");
        tbxMontoTotal.setText("");
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vaciarVenta();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirProducto;
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnCalcularCambio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JComboBox<String> cbxFormaPago;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEfectivo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormaPago;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblNFactura;
    private javax.swing.JLabel lblNetoPagar;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel pnlAccines;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JScrollPane scrProducto;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField tbxBuscarCodigo;
    private javax.swing.JTextField tbxCambio;
    private javax.swing.JTextField tbxCantidad;
    private javax.swing.JTextField tbxCliente;
    private javax.swing.JTextField tbxCodigo;
    private javax.swing.JTextField tbxDNI;
    private javax.swing.JTextField tbxDescuento;
    private javax.swing.JTextField tbxDireccion;
    private javax.swing.JTextField tbxEfectivo;
    private javax.swing.JTextField tbxFecha;
    private javax.swing.JTextField tbxIGV;
    private javax.swing.JTextField tbxMontoTotal;
    private javax.swing.JTextField tbxNFactura;
    private javax.swing.JTextField tbxNetoPagar;
    private javax.swing.JTextField tbxNumero;
    private javax.swing.JTextField tbxSubtotal;
    private javax.swing.JTextField tbxVendedor;
    // End of variables declaration//GEN-END:variables
}